from cambc import *

DIRECTIONS = [d for d in Direction if d != Direction.CENTRE]
ORTHOGONAL_DIRECTIONS = [Direction.NORTH, Direction.SOUTH, Direction.EAST, Direction.WEST]
DESTROYABLE_BUILDINGS = [None, EntityType.MARKER, EntityType.CONVEYOR, EntityType.ROAD, EntityType.SPLITTER, EntityType.ARMOURED_CONVEYOR, EntityType.BRIDGE]
CONVEYOR_BUILDINGS = [EntityType.CONVEYOR, EntityType.SPLITTER, EntityType.ARMOURED_CONVEYOR, EntityType.BRIDGE]
TURRETS = [EntityType.SENTINEL, EntityType.GUNNER]

IGNORE_ENEMY_NEIGHBORS = False # If set to true, builder bots will build harvesters next to enemy buildings
SECURE_WITH_CONVEYORS = True #False

HARVESTER_STOP_ROUND = 2000
MINIMUM_MONEY_TO_EXPLORE = 75
ENEMY_LAUNCHER_ADJACENCY_COST = 20
FRIENDLY_LAUNCHER_ADJACENCY_COST = 20

AXIONITE_START_ROUND = 500

UNREACHABLE_MEMORY_ROUNDS = 10
UNREACHABLE_CONVEYOR_MEMORY_ROUNDS = 10

ENEMY_CORE_CONVEYOR_TARGET_DISTANCE_SQUARED = 400 #225
